// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// chebyshev_filter_ring_cpp
arma::mat chebyshev_filter_ring_cpp(const arma::mat& X, const arma::vec& coeffs, double lambda_max, bool periodic);
RcppExport SEXP _rgsp_chebyshev_filter_ring_cpp(SEXP XSEXP, SEXP coeffsSEXP, SEXP lambda_maxSEXP, SEXP periodicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type periodic(periodicSEXP);
    rcpp_result_gen = Rcpp::wrap(chebyshev_filter_ring_cpp(X, coeffs, lambda_max, periodic));
    return rcpp_result_gen;
END_RCPP
}
// chebyshev_filter_cpp
arma::mat chebyshev_filter_cpp(const arma::sp_mat& L, const arma::mat& X, const arma::vec& coeffs, double lambda_max);
RcppExport SEXP _rgsp_chebyshev_filter_cpp(SEXP LSEXP, SEXP XSEXP, SEXP coeffsSEXP, SEXP lambda_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(chebyshev_filter_cpp(L, X, coeffs, lambda_max));
    return rcpp_result_gen;
END_RCPP
}
// chebyshev_filter_xptr_cpp
arma::mat chebyshev_filter_xptr_cpp(SEXP L_ptr, const arma::mat& X, const arma::vec& coeffs, double lambda_max);
RcppExport SEXP _rgsp_chebyshev_filter_xptr_cpp(SEXP L_ptrSEXP, SEXP XSEXP, SEXP coeffsSEXP, SEXP lambda_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type L_ptr(L_ptrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(chebyshev_filter_xptr_cpp(L_ptr, X, coeffs, lambda_max));
    return rcpp_result_gen;
END_RCPP
}
// laplacian_sp_xptr_cpp
SEXP laplacian_sp_xptr_cpp(const arma::sp_mat& L);
RcppExport SEXP _rgsp_laplacian_sp_xptr_cpp(SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(laplacian_sp_xptr_cpp(L));
    return rcpp_result_gen;
END_RCPP
}
// set_omp_threads_cpp
void set_omp_threads_cpp(int threads);
RcppExport SEXP _rgsp_set_omp_threads_cpp(SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    set_omp_threads_cpp(threads);
    return R_NilValue;
END_RCPP
}
// chebyshev_filter_omp_cpp
arma::mat chebyshev_filter_omp_cpp(SEXP L_ptr, const arma::mat& X, const arma::vec& coeffs, double lambda_max, int threads, int precision);
RcppExport SEXP _rgsp_chebyshev_filter_omp_cpp(SEXP L_ptrSEXP, SEXP XSEXP, SEXP coeffsSEXP, SEXP lambda_maxSEXP, SEXP threadsSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type L_ptr(L_ptrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< int >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(chebyshev_filter_omp_cpp(L_ptr, X, coeffs, lambda_max, threads, precision));
    return rcpp_result_gen;
END_RCPP
}
// dense_mat_xptr_cpp
SEXP dense_mat_xptr_cpp(const arma::mat& X);
RcppExport SEXP _rgsp_dense_mat_xptr_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(dense_mat_xptr_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// dense_matmul_xptr_cpp
arma::mat dense_matmul_xptr_cpp(SEXP A_ptr, const arma::mat& B);
RcppExport SEXP _rgsp_dense_matmul_xptr_cpp(SEXP A_ptrSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A_ptr(A_ptrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(dense_matmul_xptr_cpp(A_ptr, B));
    return rcpp_result_gen;
END_RCPP
}
// degree_cpp
arma::vec degree_cpp(const arma::sp_mat& A);
RcppExport SEXP _rgsp_degree_cpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(degree_cpp(A));
    return rcpp_result_gen;
END_RCPP
}
// laplacian_cpp
arma::sp_mat laplacian_cpp(const arma::sp_mat& A, bool normalized, bool directed);
RcppExport SEXP _rgsp_laplacian_cpp(SEXP ASEXP, SEXP normalizedSEXP, SEXP directedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< bool >::type normalized(normalizedSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    rcpp_result_gen = Rcpp::wrap(laplacian_cpp(A, normalized, directed));
    return rcpp_result_gen;
END_RCPP
}
// adjacency_ring_cpp
arma::sp_mat adjacency_ring_cpp(int n, bool periodic);
RcppExport SEXP _rgsp_adjacency_ring_cpp(SEXP nSEXP, SEXP periodicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type periodic(periodicSEXP);
    rcpp_result_gen = Rcpp::wrap(adjacency_ring_cpp(n, periodic));
    return rcpp_result_gen;
END_RCPP
}
// adjacency_grid2d_cpp
arma::sp_mat adjacency_grid2d_cpp(int nrow, int ncol, bool periodic);
RcppExport SEXP _rgsp_adjacency_grid2d_cpp(SEXP nrowSEXP, SEXP ncolSEXP, SEXP periodicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< bool >::type periodic(periodicSEXP);
    rcpp_result_gen = Rcpp::wrap(adjacency_grid2d_cpp(nrow, ncol, periodic));
    return rcpp_result_gen;
END_RCPP
}
// adjacency_grid3d_cpp
arma::sp_mat adjacency_grid3d_cpp(int nx, int ny, int nz, bool periodic);
RcppExport SEXP _rgsp_adjacency_grid3d_cpp(SEXP nxSEXP, SEXP nySEXP, SEXP nzSEXP, SEXP periodicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< int >::type ny(nySEXP);
    Rcpp::traits::input_parameter< int >::type nz(nzSEXP);
    Rcpp::traits::input_parameter< bool >::type periodic(periodicSEXP);
    rcpp_result_gen = Rcpp::wrap(adjacency_grid3d_cpp(nx, ny, nz, periodic));
    return rcpp_result_gen;
END_RCPP
}
// lanczos_filter_cpp
arma::mat lanczos_filter_cpp(const arma::sp_mat& L, const arma::mat& X, int K, Rcpp::Function kernel);
RcppExport SEXP _rgsp_lanczos_filter_cpp(SEXP LSEXP, SEXP XSEXP, SEXP KSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(lanczos_filter_cpp(L, X, K, kernel));
    return rcpp_result_gen;
END_RCPP
}
// prox_l1_cpp
arma::mat prox_l1_cpp(const arma::mat& X, double tau);
RcppExport SEXP _rgsp_prox_l1_cpp(SEXP XSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(prox_l1_cpp(X, tau));
    return rcpp_result_gen;
END_RCPP
}
// prox_tv1d_cpp
arma::vec prox_tv1d_cpp(const arma::vec& y, double lambda);
RcppExport SEXP _rgsp_prox_tv1d_cpp(SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(prox_tv1d_cpp(y, lambda));
    return rcpp_result_gen;
END_RCPP
}
// tv_denoise_fista_cpp
arma::vec tv_denoise_fista_cpp(const arma::sp_mat& L, const arma::vec& y, double lambda, int maxit, double tol, double step);
RcppExport SEXP _rgsp_tv_denoise_fista_cpp(SEXP LSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(tv_denoise_fista_cpp(L, y, lambda, maxit, tol, step));
    return rcpp_result_gen;
END_RCPP
}
// prox_graph_tv_cpp
arma::vec prox_graph_tv_cpp(const arma::vec& y, const arma::uvec& rows, const arma::uvec& cols, const arma::vec& w, double lambda, int maxit, double tau, double sigma, double tol);
RcppExport SEXP _rgsp_prox_graph_tv_cpp(SEXP ySEXP, SEXP rowsSEXP, SEXP colsSEXP, SEXP wSEXP, SEXP lambdaSEXP, SEXP maxitSEXP, SEXP tauSEXP, SEXP sigmaSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(prox_graph_tv_cpp(y, rows, cols, w, lambda, maxit, tau, sigma, tol));
    return rcpp_result_gen;
END_RCPP
}
// proj_simplex_cpp
arma::vec proj_simplex_cpp(const arma::vec& y);
RcppExport SEXP _rgsp_proj_simplex_cpp(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(proj_simplex_cpp(y));
    return rcpp_result_gen;
END_RCPP
}
// proj_simplex_rows_cpp
arma::mat proj_simplex_rows_cpp(const arma::mat& Y);
RcppExport SEXP _rgsp_proj_simplex_rows_cpp(SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(proj_simplex_rows_cpp(Y));
    return rcpp_result_gen;
END_RCPP
}
// proj_l2_ball_cpp
arma::vec proj_l2_ball_cpp(const arma::vec& y, double r);
RcppExport SEXP _rgsp_proj_l2_ball_cpp(SEXP ySEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(proj_l2_ball_cpp(y, r));
    return rcpp_result_gen;
END_RCPP
}
// prox_box_cpp
arma::vec prox_box_cpp(const arma::vec& y, double lower, double upper);
RcppExport SEXP _rgsp_prox_box_cpp(SEXP ySEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(prox_box_cpp(y, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// tikhonov_solve_cpp
arma::mat tikhonov_solve_cpp(const arma::sp_mat& L, const arma::mat& B, double tau, double tol, int maxit);
RcppExport SEXP _rgsp_tikhonov_solve_cpp(SEXP LSEXP, SEXP BSEXP, SEXP tauSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(tikhonov_solve_cpp(L, B, tau, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rgsp_chebyshev_filter_ring_cpp", (DL_FUNC) &_rgsp_chebyshev_filter_ring_cpp, 4},
    {"_rgsp_chebyshev_filter_cpp", (DL_FUNC) &_rgsp_chebyshev_filter_cpp, 4},
    {"_rgsp_chebyshev_filter_xptr_cpp", (DL_FUNC) &_rgsp_chebyshev_filter_xptr_cpp, 4},
    {"_rgsp_laplacian_sp_xptr_cpp", (DL_FUNC) &_rgsp_laplacian_sp_xptr_cpp, 1},
    {"_rgsp_set_omp_threads_cpp", (DL_FUNC) &_rgsp_set_omp_threads_cpp, 1},
    {"_rgsp_chebyshev_filter_omp_cpp", (DL_FUNC) &_rgsp_chebyshev_filter_omp_cpp, 6},
    {"_rgsp_dense_mat_xptr_cpp", (DL_FUNC) &_rgsp_dense_mat_xptr_cpp, 1},
    {"_rgsp_dense_matmul_xptr_cpp", (DL_FUNC) &_rgsp_dense_matmul_xptr_cpp, 2},
    {"_rgsp_degree_cpp", (DL_FUNC) &_rgsp_degree_cpp, 1},
    {"_rgsp_laplacian_cpp", (DL_FUNC) &_rgsp_laplacian_cpp, 3},
    {"_rgsp_adjacency_ring_cpp", (DL_FUNC) &_rgsp_adjacency_ring_cpp, 2},
    {"_rgsp_adjacency_grid2d_cpp", (DL_FUNC) &_rgsp_adjacency_grid2d_cpp, 3},
    {"_rgsp_adjacency_grid3d_cpp", (DL_FUNC) &_rgsp_adjacency_grid3d_cpp, 4},
    {"_rgsp_lanczos_filter_cpp", (DL_FUNC) &_rgsp_lanczos_filter_cpp, 4},
    {"_rgsp_prox_l1_cpp", (DL_FUNC) &_rgsp_prox_l1_cpp, 2},
    {"_rgsp_prox_tv1d_cpp", (DL_FUNC) &_rgsp_prox_tv1d_cpp, 2},
    {"_rgsp_tv_denoise_fista_cpp", (DL_FUNC) &_rgsp_tv_denoise_fista_cpp, 6},
    {"_rgsp_prox_graph_tv_cpp", (DL_FUNC) &_rgsp_prox_graph_tv_cpp, 9},
    {"_rgsp_proj_simplex_cpp", (DL_FUNC) &_rgsp_proj_simplex_cpp, 1},
    {"_rgsp_proj_simplex_rows_cpp", (DL_FUNC) &_rgsp_proj_simplex_rows_cpp, 1},
    {"_rgsp_proj_l2_ball_cpp", (DL_FUNC) &_rgsp_proj_l2_ball_cpp, 2},
    {"_rgsp_prox_box_cpp", (DL_FUNC) &_rgsp_prox_box_cpp, 3},
    {"_rgsp_tikhonov_solve_cpp", (DL_FUNC) &_rgsp_tikhonov_solve_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rgsp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
