# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chebyshev_filter_cpp <- function(L, X, coeffs, lambda_max) {
    .Call(`_rgsp_chebyshev_filter_cpp`, L, X, coeffs, lambda_max)
}

chebyshev_filter_xptr_cpp <- function(L_ptr, X, coeffs, lambda_max) {
    .Call(`_rgsp_chebyshev_filter_xptr_cpp`, L_ptr, X, coeffs, lambda_max)
}

laplacian_sp_xptr_cpp <- function(L) {
    .Call(`_rgsp_laplacian_sp_xptr_cpp`, L)
}

set_omp_threads_cpp <- function(threads) {
    invisible(.Call(`_rgsp_set_omp_threads_cpp`, threads))
}

chebyshev_filter_omp_cpp <- function(L_ptr, X, coeffs, lambda_max, threads = -1L, precision = 0L) {
    .Call(`_rgsp_chebyshev_filter_omp_cpp`, L_ptr, X, coeffs, lambda_max, threads, precision)
}

degree_cpp <- function(A) {
    .Call(`_rgsp_degree_cpp`, A)
}

laplacian_cpp <- function(A, normalized = FALSE, directed = FALSE) {
    .Call(`_rgsp_laplacian_cpp`, A, normalized, directed)
}

adjacency_ring_cpp <- function(n, periodic = TRUE) {
    .Call(`_rgsp_adjacency_ring_cpp`, n, periodic)
}

adjacency_grid2d_cpp <- function(nrow, ncol, periodic = FALSE) {
    .Call(`_rgsp_adjacency_grid2d_cpp`, nrow, ncol, periodic)
}

adjacency_grid3d_cpp <- function(nx, ny, nz, periodic = FALSE) {
    .Call(`_rgsp_adjacency_grid3d_cpp`, nx, ny, nz, periodic)
}

lanczos_filter_cpp <- function(L, X, K, kernel) {
    .Call(`_rgsp_lanczos_filter_cpp`, L, X, K, kernel)
}

prox_l1_cpp <- function(X, tau) {
    .Call(`_rgsp_prox_l1_cpp`, X, tau)
}

prox_tv1d_cpp <- function(y, lambda) {
    .Call(`_rgsp_prox_tv1d_cpp`, y, lambda)
}

tv_denoise_fista_cpp <- function(L, y, lambda, maxit = 200L, tol = 1e-6, step = 1e-1) {
    .Call(`_rgsp_tv_denoise_fista_cpp`, L, y, lambda, maxit, tol, step)
}

prox_graph_tv_cpp <- function(y, rows, cols, w, lambda, maxit = 300L, tau = 0.5, sigma = 0.5, tol = 1e-6) {
    .Call(`_rgsp_prox_graph_tv_cpp`, y, rows, cols, w, lambda, maxit, tau, sigma, tol)
}

proj_simplex_cpp <- function(y) {
    .Call(`_rgsp_proj_simplex_cpp`, y)
}

proj_l2_ball_cpp <- function(y, r) {
    .Call(`_rgsp_proj_l2_ball_cpp`, y, r)
}

prox_box_cpp <- function(y, lower, upper) {
    .Call(`_rgsp_prox_box_cpp`, y, lower, upper)
}

tikhonov_solve_cpp <- function(L, B, tau, tol = 1e-6, maxit = 1000L) {
    .Call(`_rgsp_tikhonov_solve_cpp`, L, B, tau, tol, maxit)
}

